### ISSUE TITLE
Markdown is cool

### ISSUE THREAD

**Issue by kirakernel** [superz80pc/Markdown#1]
The background color should be `#ffffff` for light mode and `#0d1117` for dark mode.
The background color should be `#0969DA` for light mode and `#0d1117` for dark mode.
The background color should be `rgb(9, 105, 218)` for light mode and `#0d1117` for dark mode.
The background color should be `hsl(212, 92%, 45%)` for light mode and `#0d1117` for dark mode.

**Comment by kirakernel** [comment]
Lista de tarefas:
- [x] #739
- [ ] https://github.com/octo-org/octo-repo/issues/740
- [ ] Add delight to the experience when all tasks are complete :tada:

**Comment by kirakernel** [comment]
@superkake What do you think about these updates?

**Comment by ghost** [comment]
@superz80pc looks great for me, man!

**Comment by kirakernel** [comment]
Very good study:+1:
